server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://${DB_SERVER:localhost}/${MYSQL_DATABASE:contact}?createDatabaseIfNotExist=true
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yml