CREATE TABLE IF NOT EXISTS PERSON_ADDRESS
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CITY VARCHAR(15),
    STREET VARCHAR(15),
    POSTCODE VARCHAR(15),
    PERSON_ID BIGINT NOT NULL,
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON_CONTACT (ID)
)