CREATE TABLE IF NOT EXISTS PHONE_NUMBER
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    IS_PRIMARY BOOLEAN,
    PHONE VARCHAR(15),
    PERSON_ID BIGINT NOT NULL,
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON_CONTACT (ID)
)