CREATE TABLE IF NOT EXISTS PERSON_EMAIL
(
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    IS_PRIMARY BOOLEAN,
    EMAIL VARCHAR(15),
    PERSON_ID BIGINT NOT NULL,
    FOREIGN KEY (PERSON_ID) REFERENCES PERSON_CONTACT (ID)
)